### ISSUE TITLE
Not shimming wasi:http

### ISSUE THREAD

**Issue by James-Mart** [DougAnderson444/rollup-plugin-wit-component#2]
Why don't you shim `wasi:http`?

**Comment by DougAnderson444** [comment]
No particular reason other than I didn't really need `http` (yet?) because I was using wasm as an "http-free" sandbox to run un-trusted code on your data.

But there are other ways to handle "_hey, this component you are loading has access to the internet_", so it could probably be included at this level.

I know the [extism](https://extism.org/) crew had `http` turned off by default on their wasm implementation, so that is where I started too. 

Happy to hear your thoughts, thanks for the poke :)

**Comment by James-Mart** [comment]
Ah, makes sense. 

Perhaps you could shims everything by default and allow users to manually disable shims, similar to [wasi-virt](https://github.com/bytecodealliance/WASI-Virt?tab=readme-ov-file#api), something like:
```
const component = await import('rollup-plugin-wit-component');
component.disable('wasi:http').load(bytes, importables);
```
